# Generated by Django 2.1 on 2019-08-05 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceUuid', models.CharField(max_length=50)),
                ('deviceName', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=15)),
                ('ipAddr', models.CharField(default='ip', max_length=250)),
                ('macAddr', models.CharField(default='mac', max_length=250)),
                ('os', models.CharField(max_length=35)),
                ('processor', models.CharField(max_length=80)),
                ('cpu', models.CharField(max_length=10)),
                ('memoryCapacity', models.CharField(max_length=10)),
                ('registry_StartupCommand', models.TextField(blank=True)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField()),
                ('file_hash', models.CharField(max_length=100)),
                ('peutils_packed', models.CharField(blank=True, max_length=200)),
                ('signer', models.CharField(blank=True, max_length=300)),
                ('create_time', models.DateTimeField(blank=True)),
                ('modified_time', models.DateTimeField(blank=True)),
                ('accessed_time', models.DateTimeField(blank=True)),
                ('file_state', models.IntegerField(blank=True, null=True)),
                ('pefile_txt', models.IntegerField(blank=True, null=True)),
                ('printablestr_txt', models.IntegerField(blank=True, null=True)),
                ('entropy', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('byte_distribution', models.TextField(blank=True)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ScanningRecord',
            fields=[
                ('scan_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('normal_option', models.BooleanField()),
                ('advance_option', models.BooleanField()),
                ('customized_option', models.BooleanField()),
                ('score', models.IntegerField(default=0)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Computer')),
            ],
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='scanningRecord_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.ScanningRecord'),
        ),
    ]
