# Generated by Django 2.1 on 2019-08-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='latest_scan_score',
            field=models.IntegerField(default=0),
        ),
    ]
