# Generated by Django 2.1 on 2019-08-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinfo',
            name='pefile_txt_filename',
        ),
        migrations.RemoveField(
            model_name='fileinfo',
            name='printablestr_txt_filename',
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='pefile_txt',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='printablestr_txt',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='computer',
            name='ipAddr',
            field=models.CharField(default='ip', max_length=250),
        ),
        migrations.AlterField(
            model_name='computer',
            name='macAddr',
            field=models.CharField(default='mac', max_length=250),
        ),
    ]
