# Generated by Django 2.1 on 2019-08-04 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190804_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanningrecord_fileinfo',
            name='fileInfo_id',
        ),
        migrations.RemoveField(
            model_name='scanningrecord_fileinfo',
            name='scanningRecord_id',
        ),
        migrations.RemoveField(
            model_name='fileinfo',
            name='members',
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='scanningRecord_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.ScanningRecord'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ScanningRecord_fileInfo',
        ),
    ]
