# Generated by Django 2.1 on 2019-08-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20190804_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='entropy',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
    ]
