# Generated by Django 2.1 on 2019-08-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20190817_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='uploaded_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
