# Generated by Django 2.1 on 2019-08-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20190804_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='file_state',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='pefile_txt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='printablestr_txt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
