# Generated by Django 2.1 on 2019-11-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20191117_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinfo',
            name='file_magic',
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='accessed_time',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='create_time',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='link_date',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='modified_time',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='pe_timeDateStamp',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='signing_date',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
