# Generated by Django 2.1 on 2019-11-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20191118_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanningrecord',
            name='end_time',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='scanningrecord',
            name='start_time',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
