# Generated by Django 2.1 on 2019-11-24 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20191123_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinfo',
            name='file_state',
        ),
    ]
