# Generated by Django 2.1 on 2019-11-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20191124_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='accessed_time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='counter_signer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='create_time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='file_version',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='link_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='machine_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='modified_time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='pe_exports',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='pe_imports',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='pe_sections',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='prod_version',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='product',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='signature_verification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='signer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='signing_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
