# Generated by Django 2.1 on 2019-11-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20191127_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='counter_signer',
            field=models.TextField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='pe_exports',
            field=models.TextField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='pe_imports',
            field=models.TextField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='pe_sections',
            field=models.TextField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='signer',
            field=models.TextField(blank=True, default=[]),
        ),
    ]
