# Generated by Django 2.1 on 2019-11-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20191127_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='file_state',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
