# Generated by Django 2.1 on 2019-11-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_fileinfo_file_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
