# Generated by Django 2.1 on 2019-10-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0002_fileinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='accessed_time',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='create_time',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='link_date',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='modified_time',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='signing_date',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
