# Generated by Django 2.1 on 2019-10-14 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0003_auto_20191014_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='upload_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploadFile.File'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='pe_timeDateStamp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
