# Generated by Django 2.1 on 2019-10-14 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0004_auto_20191014_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='upload_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploadFile.File'),
        ),
    ]
