# Generated by Django 2.1 on 2019-10-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0005_auto_20191014_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinfo',
            name='file_state',
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='counter_signer',
            field=models.TextField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='pe_exports',
            field=models.TextField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='pe_imports',
            field=models.TextField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='signer',
            field=models.TextField(blank=True, default=[]),
        ),
    ]
