# Generated by Django 2.1 on 2019-06-09 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='computer_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(max_length=20)),
                ('computer_ip', models.GenericIPAddressField()),
                ('mac_addr', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='file_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_info_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='scanning_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='scanning_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_sequence', models.IntegerField()),
                ('scanning_start_time', models.DateTimeField()),
                ('scanning_end_time', models.DateTimeField()),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.computer_list')),
            ],
        ),
        migrations.AddField(
            model_name='scanning_details',
            name='scanning_history_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.scanning_history'),
        ),
        migrations.AddField(
            model_name='file_info',
            name='scanning_details_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.scanning_details'),
        ),
    ]
