# Generated by Django 2.2.2 on 2019-06-15 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='computer_list',
            new_name='computerList',
        ),
        migrations.RenameModel(
            old_name='file_info',
            new_name='fileInfo',
        ),
        migrations.RenameModel(
            old_name='scanning_details',
            new_name='scanningDetails',
        ),
        migrations.RenameModel(
            old_name='scanning_history',
            new_name='scanningHistory',
        ),
        migrations.AlterModelOptions(
            name='scanningdetails',
            options={'verbose_name_plural': 'Scanning_details'},
        ),
        migrations.RenameField(
            model_name='computerlist',
            old_name='computer_ip',
            new_name='computerIp',
        ),
        migrations.RenameField(
            model_name='computerlist',
            old_name='computer_name',
            new_name='computerName',
        ),
        migrations.RenameField(
            model_name='computerlist',
            old_name='mac_addr',
            new_name='macAddr',
        ),
    ]
