# Generated by Django 2.2.2 on 2019-06-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20190615_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerlist',
            name='memoryCapacity',
            field=models.CharField(default='0MB', max_length=30),
        ),
        migrations.AddField(
            model_name='computerlist',
            name='os',
            field=models.CharField(default='os information', max_length=30),
        ),
        migrations.AddField(
            model_name='computerlist',
            name='processorName',
            field=models.CharField(default='Processor Name', max_length=20),
        ),
    ]
