# Generated by Django 2.2.2 on 2019-06-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_auto_20190619_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanningdetails',
            old_name='options',
            new_name='fileName',
        ),
    ]
