# Generated by Django 2.1 on 2019-08-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='companyName',
            field=models.CharField(default='company1', max_length=50),
            preserve_default=False,
        ),
    ]
