# Generated by Django 2.1 on 2019-08-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_companyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='companyURL',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='companyName',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
